/**
 * Deterministic Northline Audio product catalog (~40 SKUs).
 * Imported by prisma/seed.ts — keep SKUs stable for tests and demos.
 */

export type SeedProduct = {
  sku: string;
  name: string;
  description: string;
  pricePaise: number;
  costPaise: number;
  category: string;
  tags: string[];
  metadata: {
    features: string[];
    useCases: string[];
    catalogRole?: "primary" | "attach";
    demoPrimary?: boolean;
  };
  image: string;
  imageAlt: string;
  attachSku?: string;
  attachRate?: number;
  inventory: number;
};

const IMG = {
  headphones: "/products/halo-anc.png",
  headphonesAlt: "Charcoal over-ear headphones on a neutral background",
  earbuds: "/products/drift-buds.png",
  earbudsAlt: "True wireless earbuds in an open charging case",
  speaker: "/products/field-speaker.png",
  speakerAlt: "Compact cylindrical Bluetooth speaker",
  accessory: "/products/halo-case.png",
  accessoryAlt: "Hard-shell audio carry case",
} as const;

/** Original four products — preserved for existing agent, checkout, and recovery tests. */
const CORE_PRODUCTS: SeedProduct[] = [
  {
    sku: "halo-anc",
    name: "Northline Halo ANC",
    description: "Over-ear hybrid noise cancelling for long haul flights",
    pricePaise: 749_000,
    costPaise: 512_000,
    category: "headphones",
    tags: ["anc", "headphones", "flight", "travel", "wireless"],
    metadata: {
      features: ["anc", "wireless", "noise-cancelling"],
      useCases: ["travel", "flight"],
      catalogRole: "primary",
      demoPrimary: true,
    },
    image: IMG.headphones,
    imageAlt: "Matte charcoal Northline Halo over-ear headphones",
    attachSku: "halo-case",
    attachRate: 0.41,
    inventory: 120,
  },
  {
    sku: "halo-case",
    name: "Halo hard case",
    description: "Crush-resistant travel shell sized for Halo cups",
    pricePaise: 79_000,
    costPaise: 31_000,
    category: "accessory",
    tags: ["case", "travel", "accessory", "headphones"],
    metadata: {
      features: ["travel", "protection"],
      useCases: ["travel"],
      catalogRole: "attach",
    },
    image: IMG.accessory,
    imageAlt: "Charcoal hard-shell headphone travel case",
    inventory: 200,
  },
  {
    sku: "drift-buds",
    name: "Northline Drift buds",
    description: "Compact ANC earbuds with a 28-hour case",
    pricePaise: 299_000,
    costPaise: 184_000,
    category: "earbuds",
    tags: ["anc", "earbuds", "compact", "commute", "wireless"],
    metadata: {
      features: ["anc", "compact", "wireless", "noise-cancelling"],
      useCases: ["commute", "office"],
      catalogRole: "primary",
    },
    image: IMG.earbuds,
    imageAlt: "Charcoal true wireless earbuds in an open charging case",
    attachSku: "drift-case-hard",
    attachRate: 0.38,
    inventory: 95,
  },
  {
    sku: "field-speaker",
    name: "Northline Field speaker",
    description: "Portable Bluetooth speaker with 12-hour battery",
    pricePaise: 399_000,
    costPaise: 246_000,
    category: "speaker",
    tags: ["speaker", "gift", "portable", "bluetooth", "wireless"],
    metadata: {
      features: ["portable", "wireless", "bluetooth"],
      useCases: ["gift", "outdoor"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Compact cylindrical charcoal Bluetooth speaker",
    inventory: 88,
  },
];

const EXPANDED_PRODUCTS: SeedProduct[] = [
  // Over-ear headphones
  {
    sku: "studio-open",
    name: "Northline Studio Open",
    description: "Open-back over-ear headphones tuned for mixing and critical listening",
    pricePaise: 549_000,
    costPaise: 361_000,
    category: "headphones",
    tags: ["headphones", "wired", "studio", "audiophile"],
    metadata: {
      features: ["wired", "open-back", "studio"],
      useCases: ["studio", "home"],
      catalogRole: "primary",
    },
    image: IMG.headphones,
    imageAlt: IMG.headphonesAlt,
    inventory: 64,
  },
  {
    sku: "commute-lite",
    name: "Northline Commute Lite",
    description: "Lightweight wired over-ears for daily desk and transit use",
    pricePaise: 249_000,
    costPaise: 162_000,
    category: "headphones",
    tags: ["headphones", "wired", "commute", "affordable"],
    metadata: {
      features: ["wired", "lightweight"],
      useCases: ["commute", "office"],
      catalogRole: "primary",
    },
    image: IMG.headphones,
    imageAlt: IMG.headphonesAlt,
    inventory: 110,
  },
  {
    sku: "bassline-over",
    name: "Northline Bassline Over",
    description: "Closed-back over-ears with extended low-end for hip-hop and EDM",
    pricePaise: 429_000,
    costPaise: 278_000,
    category: "headphones",
    tags: ["headphones", "wireless", "bass"],
    metadata: {
      features: ["wireless", "bass", "bluetooth"],
      useCases: ["home", "commute"],
      catalogRole: "primary",
    },
    image: IMG.headphones,
    imageAlt: IMG.headphonesAlt,
    inventory: 72,
  },
  // ANC headphones (premium tier priced above common desk budgets)
  {
    sku: "transit-max-anc",
    name: "Northline Transit Max ANC",
    description: "Flagship adaptive ANC over-ears with multi-point and 40-hour battery",
    pricePaise: 1_899_000,
    costPaise: 1_234_000,
    category: "headphones",
    tags: ["anc", "headphones", "premium", "travel", "wireless"],
    metadata: {
      features: ["anc", "wireless", "noise-cancelling", "premium"],
      useCases: ["travel", "flight"],
      catalogRole: "primary",
    },
    image: IMG.headphones,
    imageAlt: "Premium matte black ANC over-ear headphones",
    attachSku: "transit-shell",
    attachRate: 0.36,
    inventory: 48,
  },
  {
    sku: "quietcore-fold",
    name: "Northline QuietCore Fold",
    description: "Fold-flat ANC over-ears with airline adapter pouch included",
    pricePaise: 1_649_000,
    costPaise: 1_072_000,
    category: "headphones",
    tags: ["anc", "headphones", "travel", "foldable", "wireless"],
    metadata: {
      features: ["anc", "wireless", "noise-cancelling", "foldable"],
      useCases: ["travel", "flight"],
      catalogRole: "primary",
    },
    image: IMG.headphones,
    imageAlt: "Foldable ANC headphones with travel pouch",
    attachSku: "transit-shell",
    attachRate: 0.33,
    inventory: 56,
  },
  {
    sku: "cabin-comfort-anc",
    name: "Northline Cabin Comfort ANC",
    description: "Pressure-relief ANC tuned for long-haul cabin noise profiles",
    pricePaise: 1_699_000,
    costPaise: 1_105_000,
    category: "headphones",
    tags: ["anc", "headphones", "flight", "travel", "wireless"],
    metadata: {
      features: ["anc", "wireless", "noise-cancelling"],
      useCases: ["flight", "travel"],
      catalogRole: "primary",
    },
    image: IMG.headphones,
    imageAlt: "Over-ear ANC headphones optimized for air travel",
    inventory: 52,
  },
  // Wireless earbuds
  {
    sku: "drift-sport",
    name: "Northline Drift Sport",
    description: "IPX5 ANC earbuds with ear hooks for runs and gym sessions",
    pricePaise: 349_000,
    costPaise: 218_000,
    category: "earbuds",
    tags: ["earbuds", "anc", "sport", "gym", "wireless", "sweat-resistant"],
    metadata: {
      features: ["anc", "wireless", "sweat-resistant", "sport"],
      useCases: ["gym", "running"],
      catalogRole: "primary",
    },
    image: IMG.earbuds,
    imageAlt: "Sport wireless earbuds with stabilizing ear hooks",
    attachSku: "drift-case-hard",
    attachRate: 0.35,
    inventory: 102,
  },
  {
    sku: "drift-mini",
    name: "Northline Drift Mini",
    description: "Entry true wireless earbuds with 22-hour total battery",
    pricePaise: 199_000,
    costPaise: 128_000,
    category: "earbuds",
    tags: ["earbuds", "wireless", "compact", "affordable"],
    metadata: {
      features: ["wireless", "compact", "bluetooth"],
      useCases: ["commute", "casual"],
      catalogRole: "primary",
    },
    image: IMG.earbuds,
    imageAlt: "Small true wireless earbuds in a compact case",
    inventory: 140,
  },
  {
    sku: "drift-pro",
    name: "Northline Drift Pro",
    description: "LDAC-ready premium buds with adaptive ANC and spatial audio",
    pricePaise: 599_000,
    costPaise: 384_000,
    category: "earbuds",
    tags: ["earbuds", "anc", "premium", "wireless"],
    metadata: {
      features: ["anc", "wireless", "premium", "noise-cancelling", "hi-res"],
      useCases: ["travel", "office"],
      catalogRole: "primary",
    },
    image: IMG.earbuds,
    imageAlt: "Premium metallic wireless earbuds in charging case",
    attachSku: "drift-case-hard",
    attachRate: 0.42,
    inventory: 61,
  },
  {
    sku: "drift-open",
    name: "Northline Drift Open",
    description: "Open-ear wireless buds that keep you aware on city walks",
    pricePaise: 279_000,
    costPaise: 178_000,
    category: "earbuds",
    tags: ["earbuds", "wireless", "open-ear", "commute"],
    metadata: {
      features: ["wireless", "open-ear", "bluetooth"],
      useCases: ["commute", "walking"],
      catalogRole: "primary",
    },
    image: IMG.earbuds,
    imageAlt: "Open-ear wireless earbuds resting outside the ear",
    inventory: 84,
  },
  {
    sku: "pulse-buds",
    name: "Northline Pulse Buds",
    description: "Bass-forward wireless earbuds with punchy 10mm drivers",
    pricePaise: 249_000,
    costPaise: 159_000,
    category: "earbuds",
    tags: ["earbuds", "wireless", "bass", "affordable"],
    metadata: {
      features: ["wireless", "bass", "bluetooth"],
      useCases: ["commute", "casual"],
      catalogRole: "primary",
    },
    image: IMG.earbuds,
    imageAlt: "Wireless earbuds with bold bass tuning",
    inventory: 118,
  },
  // Wired / IEM earbuds
  {
    sku: "canal-pro-iem",
    name: "Northline Canal Pro IEM",
    description: "Triple-driver wired IEMs with detachable MMCX cable",
    pricePaise: 449_000,
    costPaise: 292_000,
    category: "earbuds",
    tags: ["earbuds", "wired", "iem", "audiophile"],
    metadata: {
      features: ["wired", "iem", "detachable-cable"],
      useCases: ["studio", "stage"],
      catalogRole: "primary",
    },
    image: IMG.earbuds,
    imageAlt: "In-ear monitors with braided detachable cable",
    inventory: 45,
  },
  {
    sku: "stage-monitor",
    name: "Northline Stage Monitor",
    description: "Dual-driver wired IEMs for live monitoring and rehearsal",
    pricePaise: 329_000,
    costPaise: 214_000,
    category: "earbuds",
    tags: ["earbuds", "wired", "iem", "stage"],
    metadata: {
      features: ["wired", "iem", "stage"],
      useCases: ["stage", "rehearsal"],
      catalogRole: "primary",
    },
    image: IMG.earbuds,
    imageAlt: "Stage in-ear monitors with over-ear cable routing",
    inventory: 58,
  },
  {
    sku: "daily-wired",
    name: "Northline Daily Wired",
    description: "Affordable USB-C wired earbuds with inline mic for calls",
    pricePaise: 89_000,
    costPaise: 52_000,
    category: "earbuds",
    tags: ["earbuds", "wired", "affordable", "calls"],
    metadata: {
      features: ["wired", "usb-c", "inline-mic"],
      useCases: ["office", "calls"],
      catalogRole: "primary",
    },
    image: IMG.earbuds,
    imageAlt: "Simple wired USB-C earbuds with inline remote",
    inventory: 175,
  },
  // Portable Bluetooth speakers
  {
    sku: "field-mini",
    name: "Northline Field Mini",
    description: "Palm-size Bluetooth speaker for desks and weekend bags",
    pricePaise: 149_000,
    costPaise: 94_000,
    category: "speaker",
    tags: ["speaker", "portable", "bluetooth", "affordable"],
    metadata: {
      features: ["portable", "bluetooth", "wireless"],
      useCases: ["desk", "travel"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Palm-sized portable Bluetooth speaker",
    inventory: 132,
  },
  {
    sku: "field-rugged",
    name: "Northline Field Rugged",
    description: "IP67 rugged speaker with strap loop for hikes and beach days",
    pricePaise: 549_000,
    costPaise: 356_000,
    category: "speaker",
    tags: ["speaker", "portable", "bluetooth", "waterproof", "outdoor", "beach"],
    metadata: {
      features: ["portable", "bluetooth", "waterproof", "rugged"],
      useCases: ["beach", "outdoor", "hiking"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Rugged waterproof Bluetooth speaker with carry strap",
    inventory: 76,
  },
  {
    sku: "field-party",
    name: "Northline Field Party",
    description: "360° portable speaker with party boost and 18-hour playtime",
    pricePaise: 799_000,
    costPaise: 519_000,
    category: "speaker",
    tags: ["speaker", "portable", "bluetooth", "party", "premium"],
    metadata: {
      features: ["portable", "bluetooth", "360-audio", "premium"],
      useCases: ["party", "outdoor"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Large cylindrical party Bluetooth speaker",
    inventory: 42,
  },
  {
    sku: "tide-speaker",
    name: "Northline Tide Speaker",
    description: "Float-ready waterproof speaker for poolside and beach trips",
    pricePaise: 459_000,
    costPaise: 298_000,
    category: "speaker",
    tags: ["speaker", "portable", "bluetooth", "beach", "waterproof"],
    metadata: {
      features: ["portable", "bluetooth", "waterproof", "float"],
      useCases: ["beach", "pool"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Waterproof speaker designed for beach and pool use",
    inventory: 68,
  },
  // Home speakers
  {
    sku: "shelf-one",
    name: "Northline Shelf One",
    description: "Bookshelf speaker pair with warm vocal tuning for living rooms",
    pricePaise: 899_000,
    costPaise: 584_000,
    category: "speaker",
    tags: ["speaker", "home", "bookshelf", "wired"],
    metadata: {
      features: ["home-audio", "bookshelf", "wired"],
      useCases: ["home", "living-room"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Pair of bookshelf home speakers",
    inventory: 36,
  },
  {
    sku: "room-fill",
    name: "Northline Room Fill",
    description: "Wi-Fi stereo pair with room calibration for medium-sized spaces",
    pricePaise: 1_499_000,
    costPaise: 974_000,
    category: "speaker",
    tags: ["speaker", "home", "premium", "wireless"],
    metadata: {
      features: ["home-audio", "wireless", "premium", "stereo"],
      useCases: ["home", "entertainment"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Premium wireless stereo home speaker pair",
    inventory: 28,
  },
  {
    sku: "desk-wave",
    name: "Northline Desk Wave",
    description: "Compact powered desktop speaker with USB-C input for monitors",
    pricePaise: 599_000,
    costPaise: 389_000,
    category: "speaker",
    tags: ["speaker", "home", "desk", "usb-c"],
    metadata: {
      features: ["home-audio", "desk", "usb-c"],
      useCases: ["desk", "office"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Compact desktop speaker for workstation setups",
    inventory: 54,
  },
  // Soundbars
  {
    sku: "arc-soundbar",
    name: "Northline Arc Soundbar",
    description: "3.1 soundbar with wireless sub for TV and console setups",
    pricePaise: 1_199_000,
    costPaise: 779_000,
    category: "soundbar",
    tags: ["soundbar", "home", "tv", "premium"],
    metadata: {
      features: ["soundbar", "wireless-sub", "hdmi-arc"],
      useCases: ["home", "tv"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Soundbar with wireless subwoofer for TV audio",
    inventory: 32,
  },
  {
    sku: "arc-slim",
    name: "Northline Arc Slim",
    description: "Low-profile soundbar for apartments and bedroom TVs",
    pricePaise: 699_000,
    costPaise: 454_000,
    category: "soundbar",
    tags: ["soundbar", "home", "tv", "compact"],
    metadata: {
      features: ["soundbar", "compact", "bluetooth"],
      useCases: ["home", "bedroom"],
      catalogRole: "primary",
    },
    image: IMG.speaker,
    imageAlt: "Slim soundbar beneath a wall-mounted TV",
    inventory: 44,
  },
  // Headphone cases
  {
    sku: "transit-shell",
    name: "Northline Transit Shell",
    description: "Universal hard case for fold-flat and full-size over-ear headphones",
    pricePaise: 129_000,
    costPaise: 48_000,
    category: "accessory",
    tags: ["case", "headphones", "travel", "accessory"],
    metadata: {
      features: ["protection", "travel"],
      useCases: ["travel"],
      catalogRole: "attach",
    },
    image: IMG.accessory,
    imageAlt: "Universal hard-shell case for over-ear headphones",
    inventory: 160,
  },
  {
    sku: "studio-pouch",
    name: "Northline Studio Pouch",
    description: "Quilted soft pouch for studio headphones between sessions",
    pricePaise: 69_000,
    costPaise: 26_000,
    category: "accessory",
    tags: ["case", "headphones", "studio", "accessory"],
    metadata: {
      features: ["protection", "soft-case"],
      useCases: ["studio", "home"],
      catalogRole: "attach",
    },
    image: IMG.accessory,
    imageAlt: "Soft quilted pouch for headphone storage",
    inventory: 190,
  },
  // Earbud cases
  {
    sku: "drift-case-s",
    name: "Northline Drift silicone case",
    description: "Soft silicone sleeve that fits Drift and Pulse charging cases",
    pricePaise: 49_000,
    costPaise: 18_000,
    category: "accessory",
    tags: ["case", "earbuds", "accessory"],
    metadata: {
      features: ["protection", "silicone"],
      useCases: ["commute", "travel"],
      catalogRole: "attach",
    },
    image: IMG.accessory,
    imageAlt: "Silicone protective sleeve for earbud charging case",
    inventory: 220,
  },
  {
    sku: "drift-case-hard",
    name: "Northline Drift hard case",
    description: "Impact shell for Drift-family charging cases and spare tips",
    pricePaise: 79_000,
    costPaise: 29_000,
    category: "accessory",
    tags: ["case", "earbuds", "travel", "accessory"],
    metadata: {
      features: ["protection", "travel"],
      useCases: ["travel", "gym"],
      catalogRole: "attach",
    },
    image: IMG.accessory,
    imageAlt: "Hard-shell case sized for true wireless earbud cases",
    inventory: 185,
  },
  // Chargers
  {
    sku: "dual-dock",
    name: "Northline Dual Dock",
    description: "GaN dual USB-C dock that charges phone and buds simultaneously",
    pricePaise: 249_000,
    costPaise: 149_000,
    category: "charger",
    tags: ["charger", "usb-c", "gan", "accessory"],
    metadata: {
      features: ["usb-c", "gan", "dual-port"],
      useCases: ["travel", "desk"],
      catalogRole: "primary",
    },
    image: IMG.accessory,
    imageAlt: "Compact dual-port USB-C GaN charger",
    inventory: 98,
  },
  {
    sku: "travel-charge-20w",
    name: "Northline Travel Charge 20W",
    description: "Fold-pin 20W USB-C wall adapter for carry-on kits",
    pricePaise: 99_000,
    costPaise: 58_000,
    category: "charger",
    tags: ["charger", "usb-c", "travel", "affordable"],
    metadata: {
      features: ["usb-c", "travel", "compact"],
      useCases: ["travel"],
      catalogRole: "primary",
    },
    image: IMG.accessory,
    imageAlt: "Foldable 20W USB-C travel wall charger",
    inventory: 150,
  },
  // USB-C / audio cables
  {
    sku: "usbc-audio-cable",
    name: "Northline USB-C audio cable 1.2m",
    description: "Shielded USB-C to 3.5mm cable for laptops and phones without a jack",
    pricePaise: 79_000,
    costPaise: 34_000,
    category: "cable",
    tags: ["cable", "usb-c", "audio", "accessory"],
    metadata: {
      features: ["usb-c", "audio", "dac-ready"],
      useCases: ["travel", "office"],
      catalogRole: "primary",
    },
    image: IMG.accessory,
    imageAlt: "USB-C to 3.5mm audio adapter cable",
    inventory: 210,
  },
  {
    sku: "braided-usbc-2m",
    name: "Northline braided USB-C 2m",
    description: "Braided charge and data cable rated for 60W PD",
    pricePaise: 59_000,
    costPaise: 28_000,
    category: "cable",
    tags: ["cable", "usb-c", "charging", "affordable"],
    metadata: {
      features: ["usb-c", "braided", "pd"],
      useCases: ["desk", "travel"],
      catalogRole: "primary",
    },
    image: IMG.accessory,
    imageAlt: "Braided two-meter USB-C charging cable",
    inventory: 240,
  },
  // Audio adapters
  {
    sku: "bt-aux-adapter",
    name: "Northline BT Aux adapter",
    description: "Bluetooth receiver that adds wireless audio to car and desk aux ports",
    pricePaise: 129_000,
    costPaise: 72_000,
    category: "adapter",
    tags: ["adapter", "bluetooth", "aux", "accessory"],
    metadata: {
      features: ["bluetooth", "aux", "receiver"],
      useCases: ["car", "desk"],
      catalogRole: "primary",
    },
    image: IMG.accessory,
    imageAlt: "Bluetooth aux receiver with 3.5mm plug",
    inventory: 125,
  },
  {
    sku: "usbc-dac-lite",
    name: "Northline USB-C DAC Lite",
    description: "Compact USB-C DAC with 3.5mm out for hi-res playback on laptops",
    pricePaise: 199_000,
    costPaise: 118_000,
    category: "adapter",
    tags: ["adapter", "usb-c", "dac", "audiophile"],
    metadata: {
      features: ["usb-c", "dac", "hi-res"],
      useCases: ["desk", "travel"],
      catalogRole: "primary",
    },
    image: IMG.accessory,
    imageAlt: "Small USB-C digital-to-analog converter dongle",
    inventory: 87,
  },
  // Premium audio accessories
  {
    sku: "memory-foam-tips",
    name: "Northline memory foam tips 3-pack",
    description: "Slow-rebound foam tips in S/M/L for deeper seal and isolation",
    pricePaise: 59_000,
    costPaise: 22_000,
    category: "accessory",
    tags: ["accessory", "earbuds", "tips", "affordable"],
    metadata: {
      features: ["tips", "isolation", "comfort"],
      useCases: ["travel", "gym"],
      catalogRole: "attach",
    },
    image: IMG.accessory,
    imageAlt: "Three pairs of memory foam ear tips",
    inventory: 260,
  },
  {
    sku: "stand-dual",
    name: "Northline dual headphone stand",
    description: "Aluminum dual stand that keeps two pairs ready on a desk",
    pricePaise: 179_000,
    costPaise: 98_000,
    category: "accessory",
    tags: ["accessory", "headphones", "desk", "premium"],
    metadata: {
      features: ["stand", "desk", "aluminum"],
      useCases: ["desk", "studio"],
      catalogRole: "primary",
    },
    image: IMG.accessory,
    imageAlt: "Aluminum stand holding two pairs of headphones",
    inventory: 66,
  },
  {
    sku: "leather-carry",
    name: "Northline leather carry sleeve",
    description: "Full-grain sleeve for fold-flat headphones and compact speakers",
    pricePaise: 219_000,
    costPaise: 128_000,
    category: "accessory",
    tags: ["accessory", "premium", "travel", "case"],
    metadata: {
      features: ["premium", "leather", "travel"],
      useCases: ["travel", "commute"],
      catalogRole: "primary",
    },
    image: IMG.accessory,
    imageAlt: "Premium leather sleeve for portable audio gear",
    inventory: 55,
  },
];

export const NORTLINE_SEED_PRODUCTS: SeedProduct[] = [...CORE_PRODUCTS, ...EXPANDED_PRODUCTS];

export const NORTLINE_CATALOG_PRODUCT_COUNT = NORTLINE_SEED_PRODUCTS.length;

const skuSet = new Set(NORTLINE_SEED_PRODUCTS.map((product) => product.sku));
if (skuSet.size !== NORTLINE_SEED_PRODUCTS.length) {
  throw new Error("Northline catalog contains duplicate SKUs");
}
